name: Workflow Events

on:
    push:
    pull_request:
    schedule:
        - cron: '*/s * * * *' 
    workflow_dispatch:

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo "This workflow was triggered by a(n) ${{ github.event_name}}
